[build]
  publish = "gucci-clone/build"
  command = "chmod +x build.sh && ./build.sh"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "gucci-clone/build" 