[build]
  publish = "gucci-clone/build"
  command = "cd gucci-clone && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "gucci-clone/build" 